# Site settings
title: zahraazizi |زهرا عزیزی
email: engineerazizi025@gmail.com
description: دانشجوی کامپیوتر
baseurl: "http://zahraazizi.ir/"
url: "http://zahraazizi.ir"
twitter: _Karamii
github:  zahraazizi
behance: HosseinKarami
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]